### ISSUE TITLE
bond reader for paraview 5.8.1

### ISSUE THREAD

**Issue by lexiarlen** [richti83/ParaView_Reader_for_LIGGGHTS#5]
Thanks for writing these Paraview readers. I'm using the plugins available under /pre_compiled/Windows/5.8.1 to visualize bonding in LIGGGHTS_Flexible_Fibers. My .bond files export the bond force chain containing 16 variables (batom1x batom1y batom1z batom2x batom2y batom2z batom1 batom2 btype bforceX bforceY bforceZ btorqueX btorqueY btorqueZ beqdist). When I view the bond force magnitude in Paraview, it is about zero, but when I compute it directly from the .bond file and visualize in Python, it is what should be expected from my initial conditions (~1e8). 

How is force calculated in the reader? Should I be using a different version?

**Comment by richti83** [comment]
The fields are hardcoded here:
https://github.com/richti83/ParaView_Reader_for_LIGGGHTS/blob/44f0f58f46a530f99e8ae588b4a34ef8d87d2eed/reader_src/bond_reader/liggghts_bondreader.cxx#L238
You need to add the "molecule" id of the fiber between btype and bforceX, otherwise the values are assigned wrong.
